### ISSUE TITLE
Patch Method

### ISSUE THREAD

**Issue by ghost** [cuproPanda/STN#1]
"PatchOperationSequence will perform each operation in its list in sequence, aborting if an operation fails."

So what you do is check for a StuffedFloors def as the first step in the sequence (using PatchOperationTest), and then if it succeeds, it continues the sequence which removes every single def defined in the DesignationCategoryDefs and TerrainDefs folder. If it fails, it does not do that.

**Comment by cuproPanda** [comment]
I'll try it again, but I'm pretty sure I've already tried this and it either always removes the defs with or without the other mod, or throws an error upon fail.

**Comment by ghost** [comment]
I'm working with ZorbaTHut atm and I think I'll have a solution to you shortly.

**Comment by ghost** [comment]
So here's the problem: xml patches are evaluated on a per-file basis. But there's a workaround.

```
namespace STN
{
  class PatchOperationCheckForStuffed : PatchOperation
  {
    public override bool ApplyWorker(XmlDocument xml)
    {
      return ModsConfig.ActiveModsInLoadOrder.Any(mod => mod.meta.name == "Stuffed Floors");
    }
  }
}
```

```
<Operation Class="PatchOperationSequence">
 <success>Always</success>
 <operations>
  <li Class="STN.PatchOperationCheckForStuffed"></li>
  <li Class="PatchOperationRemove">
   <xpath>//TerrainDef[DefName = "TileClaystone"]</xpath>
  </li>
 </operations>
</Operation>
```

I have not tried to compile it yet, but this should be a step in the right direction.

**Comment by cuproPanda** [comment]
This is seriously awesome. It seems so obvious now, just override the ApplyWorker. Thank you!

**Comment by ghost** [comment]
Supposedly it's supposed to be 'mode.name' and not 'mod.meta.name' but you probably figured that out.

**Comment by ghost** [comment]
PMed you something important on the Ludeon forum, you should read it before finishing up your update.

**Comment by cuproPanda** [comment]
PMs go straight to my inbox, so I knew. Thank you, though, that's very important to know for the patches. Even after making my first patch I noticed a significant slowdown.
